// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQ39Ad-dVKB6yTSdLk2aB2ZiI2gP50UeQ',
    appId: '1:181921047566:web:8c499b4f720cc4039a885f',
    messagingSenderId: '181921047566',
    projectId: 'flappy-dash-d1d51',
    authDomain: 'flappy-dash-d1d51.firebaseapp.com',
    storageBucket: 'flappy-dash-d1d51.appspot.com',
    measurementId: 'G-NDN93V740C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8tgZGvZIPpzybce_9MaWym7fWBGKueiI',
    appId: '1:181921047566:android:4901101c32faa2329a885f',
    messagingSenderId: '181921047566',
    projectId: 'flappy-dash-d1d51',
    storageBucket: 'flappy-dash-d1d51.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWtWjx17e0nQvkH27JQ1UztoLpvpQ9lHs',
    appId: '1:181921047566:ios:9eef4c34c823fe879a885f',
    messagingSenderId: '181921047566',
    projectId: 'flappy-dash-d1d51',
    storageBucket: 'flappy-dash-d1d51.appspot.com',
    iosBundleId: 'games.pocket.flappydash.flappyDash',
  );
}
